-- Set foreign key checks to 0
SET FOREIGN_KEY_CHECKS=0;

-- Drop existing table if it exists
DROP TABLE IF EXISTS countries;

-- Create countries table
CREATE TABLE countries (
    code VARCHAR(2) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    full_name VARCHAR(200),
    is_member BOOLEAN DEFAULT TRUE
);

-- Insert UN member countries
INSERT INTO countries (code, name, full_name, is_member) VALUES
('AF', 'Afghanistan', 'The Islamic Republic of Afghanistan', true),
('AL', 'Albania', 'The Republic of Albania', true),
('DZ', 'Algeria', 'The People''s Democratic Republic of Algeria', true),
('AD', 'Andorra', 'The Principality of Andorra', true),
('AO', 'Angola', 'The Republic of Angola', true),
('AG', 'Antigua and Barbuda', 'Antigua and Barbuda', true),
('AR', 'Argentina', 'The Argentine Republic', true),
('AM', 'Armenia', 'The Republic of Armenia', true),
('AU', 'Australia', 'Australia', true),
('AT', 'Austria', 'The Republic of Austria', true),
('AZ', 'Azerbaijan', 'The Republic of Azerbaijan', true),
('BS', 'Bahamas', 'The Commonwealth of The Bahamas', true),
('BH', 'Bahrain', 'The Kingdom of Bahrain', true),
('BD', 'Bangladesh', 'The People''s Republic of Bangladesh', true),
('BB', 'Barbados', 'Barbados', true),
('BY', 'Belarus', 'The Republic of Belarus', true),
('BE', 'Belgium', 'The Kingdom of Belgium', true),
('BZ', 'Belize', 'Belize', true),
('BJ', 'Benin', 'The Republic of Benin', true),
('BT', 'Bhutan', 'The Kingdom of Bhutan', true),
('BO', 'Bolivia', 'The Plurinational State of Bolivia', true),
('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', true),
('BW', 'Botswana', 'The Republic of Botswana', true),
('BR', 'Brazil', 'The Federative Republic of Brazil', true),
('BN', 'Brunei', 'Brunei Darussalam', true),
('BG', 'Bulgaria', 'The Republic of Bulgaria', true),
('BF', 'Burkina Faso', 'Burkina Faso', true),
('BI', 'Burundi', 'The Republic of Burundi', true),
('CV', 'Cabo Verde', 'The Republic of Cabo Verde', true),
('KH', 'Cambodia', 'The Kingdom of Cambodia', true),
('CM', 'Cameroon', 'The Republic of Cameroon', true),
('CA', 'Canada', 'Canada', true),
('CF', 'Central African Republic', 'The Central African Republic', true),
('TD', 'Chad', 'The Republic of Chad', true),
('CL', 'Chile', 'The Republic of Chile', true),
('CN', 'China', 'The People''s Republic of China', true),
('CO', 'Colombia', 'The Republic of Colombia', true),
('KM', 'Comoros', 'The Union of the Comoros', true),
('CG', 'Congo', 'The Republic of the Congo', true),
('CR', 'Costa Rica', 'The Republic of Costa Rica', true),
('HR', 'Croatia', 'The Republic of Croatia', true),
('CU', 'Cuba', 'The Republic of Cuba', true),
('CY', 'Cyprus', 'The Republic of Cyprus', true),
('CZ', 'Czech Republic', 'The Czech Republic', true),
('CI', 'Côte d''Ivoire', 'The Republic of Côte d''Ivoire', true),
('KP', 'North Korea', 'The Democratic People''s Republic of Korea', true),
('CD', 'DR Congo', 'The Democratic Republic of the Congo', true),
('DK', 'Denmark', 'The Kingdom of Denmark', true),
('DJ', 'Djibouti', 'The Republic of Djibouti', true),
('DM', 'Dominica', 'The Commonwealth of Dominica', true),
('DO', 'Dominican Republic', 'The Dominican Republic', true),
('EC', 'Ecuador', 'The Republic of Ecuador', true),
('EG', 'Egypt', 'The Arab Republic of Egypt', true),
('SV', 'El Salvador', 'The Republic of El Salvador', true),
('GQ', 'Equatorial Guinea', 'The Republic of Equatorial Guinea', true),
('ER', 'Eritrea', 'The State of Eritrea', true),
('EE', 'Estonia', 'The Republic of Estonia', true),
('SZ', 'Eswatini', 'The Kingdom of Eswatini', true),
('ET', 'Ethiopia', 'The Federal Democratic Republic of Ethiopia', true),
('FJ', 'Fiji', 'The Republic of Fiji', true),
('FI', 'Finland', 'The Republic of Finland', true),
('FR', 'France', 'The French Republic', true),
('GA', 'Gabon', 'The Gabonese Republic', true),
('GM', 'Gambia', 'The Republic of The Gambia', true),
('GE', 'Georgia', 'Georgia', true),
('DE', 'Germany', 'The Federal Republic of Germany', true),
('GH', 'Ghana', 'The Republic of Ghana', true),
('GR', 'Greece', 'The Hellenic Republic', true),
('GD', 'Grenada', 'Grenada', true),
('GT', 'Guatemala', 'The Republic of Guatemala', true),
('GN', 'Guinea', 'The Republic of Guinea', true),
('GW', 'Guinea-Bissau', 'The Republic of Guinea-Bissau', true),
('GY', 'Guyana', 'The Co-operative Republic of Guyana', true),
('HT', 'Haiti', 'The Republic of Haiti', true),
('HN', 'Honduras', 'The Republic of Honduras', true),
('HU', 'Hungary', 'Hungary', true),
('IS', 'Iceland', 'The Republic of Iceland', true),
('IN', 'India', 'The Republic of India', true),
('ID', 'Indonesia', 'The Republic of Indonesia', true),
('IR', 'Iran', 'The Islamic Republic of Iran', true),
('IQ', 'Iraq', 'The Republic of Iraq', true),
('IE', 'Ireland', 'Ireland', true),
('IL', 'Israel', 'The State of Israel', true),
('IT', 'Italy', 'The Italian Republic', true),
('JM', 'Jamaica', 'Jamaica', true),
('JP', 'Japan', 'Japan', true),
('JO', 'Jordan', 'The Hashemite Kingdom of Jordan', true),
('KZ', 'Kazakhstan', 'The Republic of Kazakhstan', true),
('KE', 'Kenya', 'The Republic of Kenya', true),
('KI', 'Kiribati', 'The Republic of Kiribati', true),
('KW', 'Kuwait', 'The State of Kuwait', true),
('KG', 'Kyrgyzstan', 'The Kyrgyz Republic', true),
('LA', 'Laos', 'The Lao People''s Democratic Republic', true),
('LV', 'Latvia', 'The Republic of Latvia', true),
('LB', 'Lebanon', 'The Lebanese Republic', true),
('LS', 'Lesotho', 'The Kingdom of Lesotho', true),
('LR', 'Liberia', 'The Republic of Liberia', true),
('LY', 'Libya', 'The State of Libya', true),
('LI', 'Liechtenstein', 'The Principality of Liechtenstein', true),
('LT', 'Lithuania', 'The Republic of Lithuania', true),
('LU', 'Luxembourg', 'The Grand Duchy of Luxembourg', true),
('MG', 'Madagascar', 'The Republic of Madagascar', true),
('MW', 'Malawi', 'The Republic of Malawi', true),
('MY', 'Malaysia', 'Malaysia', true),
('MV', 'Maldives', 'The Republic of Maldives', true),
('ML', 'Mali', 'The Republic of Mali', true),
('MT', 'Malta', 'The Republic of Malta', true),
('MH', 'Marshall Islands', 'The Republic of the Marshall Islands', true),
('MR', 'Mauritania', 'The Islamic Republic of Mauritania', true),
('MU', 'Mauritius', 'The Republic of Mauritius', true),
('MX', 'Mexico', 'The United Mexican States', true),
('FM', 'Micronesia', 'The Federated States of Micronesia', true),
('MC', 'Monaco', 'The Principality of Monaco', true),
('MN', 'Mongolia', 'Mongolia', true),
('ME', 'Montenegro', 'Montenegro', true),
('MA', 'Morocco', 'The Kingdom of Morocco', true),
('MZ', 'Mozambique', 'The Republic of Mozambique', true),
('MM', 'Myanmar', 'The Republic of the Union of Myanmar', true),
('NA', 'Namibia', 'The Republic of Namibia', true),
('NR', 'Nauru', 'The Republic of Nauru', true),
('NP', 'Nepal', 'The Federal Democratic Republic of Nepal', true),
('NL', 'Netherlands', 'The Kingdom of the Netherlands', true),
('NZ', 'New Zealand', 'New Zealand', true),
('NI', 'Nicaragua', 'The Republic of Nicaragua', true),
('NE', 'Niger', 'The Republic of the Niger', true),
('NG', 'Nigeria', 'The Federal Republic of Nigeria', true),
('MK', 'North Macedonia', 'The Republic of North Macedonia', true),
('NO', 'Norway', 'The Kingdom of Norway', true),
('OM', 'Oman', 'The Sultanate of Oman', true),
('PK', 'Pakistan', 'The Islamic Republic of Pakistan', true),
('PW', 'Palau', 'The Republic of Palau', true),
('PA', 'Panama', 'The Republic of Panama', true),
('PG', 'Papua New Guinea', 'The Independent State of Papua New Guinea', true),
('PY', 'Paraguay', 'The Republic of Paraguay', true),
('PE', 'Peru', 'The Republic of Peru', true),
('PH', 'Philippines', 'The Republic of the Philippines', true),
('PL', 'Poland', 'The Republic of Poland', true),
('PT', 'Portugal', 'The Portuguese Republic', true),
('QA', 'Qatar', 'The State of Qatar', true),
('KR', 'South Korea', 'The Republic of Korea', true),
('MD', 'Moldova', 'The Republic of Moldova', true),
('RO', 'Romania', 'Romania', true),
('RU', 'Russia', 'The Russian Federation', true),
('RW', 'Rwanda', 'The Republic of Rwanda', true),
('KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', true),
('LC', 'Saint Lucia', 'Saint Lucia', true),
('VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', true),
('WS', 'Samoa', 'The Independent State of Samoa', true),
('SM', 'San Marino', 'The Republic of San Marino', true),
('ST', 'Sao Tome and Principe', 'The Democratic Republic of Sao Tome and Principe', true),
('SA', 'Saudi Arabia', 'The Kingdom of Saudi Arabia', true),
('SN', 'Senegal', 'The Republic of Senegal', true),
('RS', 'Serbia', 'The Republic of Serbia', true),
('SC', 'Seychelles', 'The Republic of Seychelles', true),
('SL', 'Sierra Leone', 'The Republic of Sierra Leone', true),
('SG', 'Singapore', 'The Republic of Singapore', true),
('SK', 'Slovakia', 'The Slovak Republic', true),
('SI', 'Slovenia', 'The Republic of Slovenia', true),
('SB', 'Solomon Islands', 'The Solomon Islands', true),
('SO', 'Somalia', 'The Federal Republic of Somalia', true),
('ZA', 'South Africa', 'The Republic of South Africa', true),
('SS', 'South Sudan', 'The Republic of South Sudan', true),
('ES', 'Spain', 'The Kingdom of Spain', true),
('LK', 'Sri Lanka', 'The Democratic Socialist Republic of Sri Lanka', true),
('SD', 'Sudan', 'The Republic of the Sudan', true),
('SR', 'Suriname', 'The Republic of Suriname', true),
('SE', 'Sweden', 'The Kingdom of Sweden', true),
('CH', 'Switzerland', 'The Swiss Confederation', true),
('SY', 'Syria', 'The Syrian Arab Republic', true),
('TJ', 'Tajikistan', 'The Republic of Tajikistan', true),
('TH', 'Thailand', 'The Kingdom of Thailand', true),
('TL', 'Timor-Leste', 'The Democratic Republic of Timor-Leste', true),
('TG', 'Togo', 'The Togolese Republic', true),
('TO', 'Tonga', 'The Kingdom of Tonga', true),
('TT', 'Trinidad and Tobago', 'The Republic of Trinidad and Tobago', true),
('TN', 'Tunisia', 'The Republic of Tunisia', true),
('TR', 'Turkey', 'The Republic of Turkey', true),
('TM', 'Turkmenistan', 'Turkmenistan', true),
('TV', 'Tuvalu', 'Tuvalu', true),
('UG', 'Uganda', 'The Republic of Uganda', true),
('UA', 'Ukraine', 'Ukraine', true),
('AE', 'United Arab Emirates', 'The United Arab Emirates', true),
('GB', 'United Kingdom', 'The United Kingdom of Great Britain and Northern Ireland', true),
('TZ', 'Tanzania', 'The United Republic of Tanzania', true),
('US', 'United States', 'The United States of America', true),
('UY', 'Uruguay', 'The Oriental Republic of Uruguay', true),
('UZ', 'Uzbekistan', 'The Republic of Uzbekistan', true),
('VU', 'Vanuatu', 'The Republic of Vanuatu', true),
('VE', 'Venezuela', 'The Bolivarian Republic of Venezuela', true),
('VN', 'Vietnam', 'The Socialist Republic of Viet Nam', true),
('YE', 'Yemen', 'The Republic of Yemen', true),
('ZM', 'Zambia', 'The Republic of Zambia', true),
('ZW', 'Zimbabwe', 'The Republic of Zimbabwe', true);

-- Reset foreign key checks
SET FOREIGN_KEY_CHECKS=1;
